platform :ios, '11.1'

target 'GithubSearch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GithubSearch
  pod 'Alamofire'

end
